# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'b0o/tmux-autoreload'

# Autoreload config path definition
set-option -g @tmux-autoreload-configs ~/.config/tmux/tmux.conf

# Set status bar style (foreground / background)
set -g status-style fg=white,bg=black

# ─────────────────────────────────────────────────────────────
# Left side of the status bar
set -g status-left "#(powerline tmux left)"

# Center of the status bar
#set -g status-justify centre

# Right side of the status bar
set -g status-right "#[fg=colour237,bg=black]#[fg=white,bg=colour237] #{=/40/...:pane_current_path} "

# ─────────────────────────────────────────────────────────────
# Powerline-style window list appearance

# Inactive window (normal)
set -g window-status-format "#[fg=white,bg=colour237] #[fg=white,bg=colour237]#I:#W #[fg=colour237,bg=black]"

# Active window (current)
set -g window-status-current-format "#[fg=white,bg=blue,bold] #[fg=white,bg=blue,bold]#I:#W #[fg=blue,bg=black]"

# Last window (optional)
#set -g window-status-last-format "#[fg=white,bg=cyan] 🔹 #I:#W #[fg=cyan,bg=black]"


run-shell "powerline-daemon -q"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

# enables mouse inside of tmux
set -g mouse on

# enables vi keybinds
setw -g mode-keys vi
